---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: gregos-desktop-kde
description: Greg's personalized KDE-based desktop environment image.

base-image: ghcr.io/ublue-os/aurora-dx-hwe
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: bling
    install:
      - 1password

  - type: systemd
    system:
      enabled:
        - sshd.service

  - type: default-flatpaks
    configurations:
      - scope: user
        install:
          - com.discordapp.Discord
          - com.slack.Slack
          - com.google.Chrome
          - io.gitlab.librewolf-community
          - md.obsidian.Obsidian
          - org.signal.Signal
          - us.zoom.Zoom

  - type: fonts
    fonts:
      nerd-fonts:
        - Cousine
        - DroidSansMono
        - FiraCode
        - Hack
        - Inconsolata
        - Noto
        - RobotoMono
        - Terminus
        - Ubuntu
        - JetBrainsMono
      google-fonts:
        - Roboto
        - Montserrat
        - Inter
        - Raleway
        - Nunito
        - Quicksand
        - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
