name: bluebuild

on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build GregOS
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        recipe:
          - recipe-k.yml
          - recipe-kb.yml
          - recipe-kbn.yml
          - recipe-kd.yml
          - recipe-kdb.yml
          - recipe-kdbn.yml
          - recipe-kdn.yml
          - recipe-kn.yml
    steps:
      - name: Build ${{ matrix.recipe }} image
        uses: blue-build/github-action@v1.9
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
